import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { register } from "@tokens-studio/sd-transforms";
import StyleDictionary from "style-dictionary";

register(StyleDictionary);

const root = path.dirname(fileURLToPath(import.meta.url));
const generatedDir = path.join(root, "generated");

/**
 * @param {string[]} sets
 * @returns {Promise<Map<string, string>>}
 */
async function resolveSets(sets) {
  /** @type {Map<string, string>} */
  const values = new Map();
  const formatName = `stylex/capture/${sets.join("+")}`;

  StyleDictionary.registerFormat({
    name: formatName,
    format: ({ dictionary }) => {
      for (const token of dictionary.allTokens) {
        const value = token.$value ?? token.value;
        values.set(token.path.join("."), stringifyValue(value));
      }
      return "";
    },
  });

  const sd = new StyleDictionary({
    log: { verbosity: "silent" },
    platforms: {
      capture: {
        buildPath: `${generatedDir}/`,
        files: [
          {
            destination: `.capture-${sets.join("-")}.txt`,
            format: formatName,
          },
        ],
        transformGroup: "tokens-studio",
      },
    },
    preprocessors: ["tokens-studio"],
    source: sets.map((set) => path.join(root, `${set}.json`)),
  });

  await sd.buildAllPlatforms();
  return values;
}

/**
 * @param {unknown} value
 * @returns {string}
 */
function stringifyValue(value) {
  if (typeof value === "string") {
    return value;
  }
  if (typeof value === "number") {
    return String(value);
  }
  if (Array.isArray(value)) {
    return value.map(String).join(", ");
  }
  return String(value);
}

/**
 * @param {string} value
 * @returns {string}
 */
function jsString(value) {
  return JSON.stringify(value);
}

/**
 * @param {Map<string, string>} tokens
 * @param {string} prefix
 * @returns {string[]}
 */
function keysWithPrefix(tokens, prefix) {
  return [...tokens.keys()]
    .filter((key) => key.startsWith(`${prefix}.`))
    .sort();
}

/**
 * @param {string} key
 * @param {string} prefix
 * @returns {string}
 */
function leafName(key, prefix) {
  return key.slice(prefix.length + 1).replaceAll(".", "_");
}

function varsFile(light) {
  const colorLines = keysWithPrefix(light, "color").map(
    (key) => `  ${leafName(key, "color")}: ${jsString(light.get(key))},`,
  );
  const spaceLines = keysWithPrefix(light, "space").map(
    (key) => `  ${leafName(key, "space")}: ${jsString(light.get(key))},`,
  );
  const fontLines = keysWithPrefix(light, "font").map(
    (key) => `  ${leafName(key, "font")}: ${jsString(light.get(key))},`,
  );

  return `/* Generated by tokens/build.js. Do not edit. */

import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
${colorLines.join("\n")}
});

export const fonts = stylex.defineVars({
${fontLines.join("\n")}
});

export const spacing = stylex.defineVars({
${spaceLines.join("\n")}
});
`;
}

function queriesFile(core) {
  const wide = core.get("layout.wide");
  if (!wide) {
    throw new Error("tokens/core.json must define layout.wide");
  }

  return `/* Generated by tokens/build.js. Do not edit. */

import * as stylex from "@stylexjs/stylex";

export const queries = stylex.defineConsts({
  container: ${jsString(`@container (min-width: ${wide})`)},
  wide: ${jsString(`@media (min-width: ${wide})`)},
});
`;
}

/**
 * @param {Map<string, string>} light
 * @param {Map<string, string>} dark
 */
function themesFile(light, dark) {
  const colorKeys = keysWithPrefix(light, "color");

  const lightOverrides = colorKeys.map(
    (key) => `  ${leafName(key, "color")}: ${jsString(light.get(key))},`,
  );
  const darkOverrides = colorKeys.map(
    (key) => `  ${leafName(key, "color")}: ${jsString(dark.get(key))},`,
  );
  const systemOverrides = colorKeys.map((key) => {
    const name = leafName(key, "color");
    return `  ${name}: {
    default: ${jsString(light.get(key))},
    "@media (prefers-color-scheme: dark)": ${jsString(dark.get(key))},
  },`;
  });

  return `/* Generated by tokens/build.js. Do not edit. */

import * as stylex from "@stylexjs/stylex";

import { colors } from "./tokens.stylex";

export const light = stylex.createTheme(colors, {
${lightOverrides.join("\n")}
});

export const dark = stylex.createTheme(colors, {
${darkOverrides.join("\n")}
});

export const system = stylex.createTheme(colors, {
${systemOverrides.join("\n")}
});

export const themes = { dark, light, system } as const;

export type ThemeName = keyof typeof themes;
`;
}

const light = await resolveSets(["core", "light"]);
const dark = await resolveSets(["core", "dark"]);

await mkdir(generatedDir, { recursive: true });
await writeFile(path.join(generatedDir, "tokens.stylex.ts"), varsFile(light));
await writeFile(
  path.join(generatedDir, "queries.stylex.ts"),
  queriesFile(light),
);
await writeFile(path.join(generatedDir, "themes.ts"), themesFile(light, dark));
